/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: WastingMyCars (https://sketchfab.com/zxargon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-honda-s2000-s2k-bbcc1cbb7f774b8ab9e94639a058e188
Title: [FREE] Honda S2000 - S2K
*/

import { useRef, useEffect, useState, Suspense } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'



import carScene from '../assets/s2k.glb'

const S2k = (props) => {
  const island = useRef();
  const { nodes, materials } = useGLTF(carScene)

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 43.389, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_Material006_0.geometry}
          material={materials['Material.006']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_Material005_0.geometry}
          material={materials['Material.005']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_Material009_0.geometry}
          material={materials['Material.009']}
          position={[0.001, 43.31, -56.5]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[42.758, 42.058, 42.058]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_Material005_0.geometry}
          material={materials['Material.005']}
          position={[0, 23.78, -9.813]}
          scale={[28.434, 5.973, 19.278]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022_Material016_0.geometry}
          material={materials['Material.016']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_Material_0.geometry}
          material={materials.Material}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane023_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024_Material010_0.geometry}
          material={materials['Material.010']}
          position={[0, 43.31, -275.66]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_Material_0.geometry}
          material={materials.Material}
          position={[0, 43.31, -56.627]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026_Material008_0.geometry}
          material={materials['Material.008']}
          position={[0, 21.227, -57.296]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane027_Material002_0.geometry}
          material={materials['Material.002']}
          position={[0, 21.227, -57.296]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Material014_0.geometry}
          material={materials['Material.014']}
          position={[0, 21.227, -54.501]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_Material005_0.geometry}
          material={materials['Material.005']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029_Material005_0.geometry}
          material={materials['Material.005']}
          position={[0, 43.31, -56.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle007_Material007_0.geometry}
          material={materials['Material.007']}
          position={[0, 21.227, -47.85]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle013_Material015_0.geometry}
          material={materials['Material.015']}
          position={[0, 21.227, -47.85]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle014_Material003_0.geometry}
          material={materials['Material.003']}
          position={[0, 21.227, -47.85]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Material003_0.geometry}
          material={materials['Material.003']}
          position={[0, 21.227, -54.501]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Material003_0.geometry}
          material={materials['Material.003']}
          position={[0, 21.227, -54.501]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_Material017_0.geometry}
          material={materials['Material.017']}
          position={[0, 21.227, -54.501]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_Material011_0.geometry}
          material={materials['Material.011']}
          position={[0, 22.488, -54.501]}
          rotation={[0, Math.PI / 2, 0]}
          scale={23.61}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Material013_0.geometry}
          material={materials['Material.013']}
          position={[0, 1.261, -164.184]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={4.854}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material001_0.geometry}
          material={materials['Material.001']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Material016_0.geometry}
          material={materials['Material.016']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

export default S2k;
